services:
  - type: web
    name: ggwins-site
    runtime: python
    buildCommand: ""
    startCommand: "python server.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
